# Use the (faster) container-based infrastructure, see also
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: go
go:
  - 1.8

env:
  global:
  # GITHUB_USER
  - secure: "Gh2YKPSLuCK06ji+fYccWv9sKpKRRqOq9/d0V2vxXK08qKhiB5lnUlOwKIgHYvA6Y9quPhwnoRqaXX3es4ciHq+CvoHMUBYEy4NtS5Lr/aWYvXEEaiICdcULv+991xDsudJZ8g58j20XBvBWi28GuGlcY629G8JRKqYzhRzUZ0zl9XUDEzaYzhM4yCsSRHKlY27J6/qaHBaWO3EDJKJzDBFa09HhX3G49ES3W5ArtntgsYM3I30L0KaZAKuxoXBjjLJn+MiufUwpBtFJSr7AxBICWQmHcUBkS70e8JeQkeB2a+7Xj/Z+2yiZlpHWXJlOD57zykTgWKmVzKP/ki6Ky+NGub1XDP5JyJ8QBlzRkqG8isxyl8aiC+JAKqKyhBAHIOHAcfkqoonNLoPdGiODEE56ebSjtrnUNQW4UHiO3UFHclc3HFBhzASmJgsLTa+MVZ7KBhLKaAI95P4ykVRDL+lpc6lj0IjfXUWuo1nIXX6cKtD/OaludrQhzmFUlwM5l9misLjlvEMpMA17NfE7u7jqTY3WGRdX8crKaS/8OUxMmvSolk3IC6O2PCLa97ZRbM5vB9Yv6JXcuRS/UPONfVeCWaQMNmOGeWyIcjIVUTikTjLbm1CDGKh/uR/igvCQ0JRV7MDD8R1NE75+IeY0PD0ZIiNZ5nVYJelQTY7mMCI="
  # GITHUB_AUTH_TOKEN
  - secure: "tZMezsUCNLDE1uwShen2omADxYbWv7lS21lM+GwQBSPhWQgOx9wzpegDEyV1PxoWqYqASuEPQYxA9+B80S/guCiBCXXdxbOFEbhd+Uj5PlNI2bB2AaWrUwsa3nNtM+CwKp9cikB+zOSqw24ibrpS6VNKd+gBGOOTTLj3VXvWoNGT6vmBeIqUkEc6oGto4RunQ5uz7Z8aggs/mv9Mzi2ClzPDEtb0efqrxVJpxMP/bzo0zdOh+x4gNZtVKdPHu2YjNK+bCF9S7V4g5+kXEblOMcY/zgn1UlHE14ErqCLJLf3sb+HUMS5XIMypHMX1cpKrSU9pq4/LlQGAuGMuIIghXT9CXW4+ClNH4jdYhpob1PFUYEFe1T/yD7Y9zQVPb9w5ZR/CpkO7w4ppq9QE+lVRa1+AcZyJt0HvY6X2fi7JP+c403OReKRBt9yhFFRcUXGxJbrSs+fLHpLUtGZospMrACdV31wo6KqmnlfMjTn2o8J0NQHlt1UG3/Qs/buobuQUmNCTkwwx6JMjzRPiSPC7kWHN++a2eG5QpZ/7YmOj9SE8eGCjlrdOloqkpa3cl1gW8+DBeAVkYe4dXTY7fF0wrpDZa6UObReEvpiP+D+33gkEMDzX1+W5czxxu4Bn4KBZLbes9TJLc7MPJv5+AJFmmXSXwZFcNhyt5AfdwWrM1Ts="
  # BOOTERY_URL
  - secure: "oQvKfxKj8bvtDTciNT+4xYdFsb/gi8X7vJtu0DlbTnRfZZ9dq9k5OiHs17yYF0eWkW4CE/0STXFZ3DKLTlDyd7HYbDSax13128Dt5rqqLN0K93hjQHY2FW038ZCdkHd3csuxOMt3ga3N+ZD0hxlPvXm6KIIWG9F6p+2FGKXrP1pkiH0pdgt0v9zHia0hJ4lYf9KloJHAn4bFOIoSjqEtwhoQHi+HQI1HGSc7N7TB/dIsXwru8zmQ2qiHVqffnEb60DCZa6amSnWg59ltkhlNRJc9+Ez/U6iukKukLw3+K8H9WvDcnlf2lu6Ks+zMpHthvNIO3Mhz9wUsAz+HaJaUvL5b3Y2yPnZ2jTpZ5doLjGtwYREzaK9Lo20Z94znFBVLQe9OY2/8Y0vXQOD7899gEXV/0m5blSyV4x7W9B0w8gxkMQI/O1PfZS0b3OOoqBdegDP/0Rot7J+s4i2foBlkm0Pvm4nCewCE6lhzUuTLWF6oasYQPxBAL3e2GAS7/bMFm5BgO3fydkhi3u7Vrw1S3mSgFlodLrqvttgzdatsKIGGyOx/10weiKl0GdvtjY86Vbbnsm2iRWebUworaQX5m4JDn/nDRATb0b0r5HwlxJ++MVzA7E36ZJ3/F/zjb/Ai3XHNLd8Op5gzLQRb7fug9mRwxsiB2D7ckcX7IXZ21DQ="

script:
  - SKIP=
  # Check whether files are syntactically correct.
  - "gofmt -l $(find . -name '*.go' | tr '\\n' ' ') >/dev/null"
  # Check whether files were not gofmt'ed.
  - gosrc=$(find . -name '*.go' | tr '\\n' ' '); [ $(gofmt -l $gosrc 2>&- | wc -l) -eq 0 ] || (echo 'gofmt was not run on these files:'; gofmt -l $gosrc 2>&-; false)
  - '[ "$TRAVIS_SECURE_ENV_VARS" != "true" ] || go get -u github.com/gokrazy/autoupdate/cmd/... github.com/gokrazy/tools/cmd/gokr-packer'
  - '[ "$TRAVIS_SECURE_ENV_VARS" != "true" ] || (gokr-boot -require_label=please-boot -set_label=please-merge -bootery_url=$BOOTERY_URL; ret=$?; if [ $ret -eq 0 ]; then SKIP=1; exit 0; elif [ $ret -eq 1 ]; then SKIP=1; exit 1; else true; fi)'
  - '[ "$TRAVIS_SECURE_ENV_VARS" != "true" ] || (gokr-merge -require_label=please-merge; ret=$?; if [ $ret -eq 0 ]; then exit 0; elif [ $ret -eq 1 ]; then exit 1; else true; fi)'
  # Update firmware files
  - [ $SKIP ] || go install ./cmd/gokr-update-firmware
  - [ $SKIP ] || gokr-update-firmware
  # update pull request
  - '[ $SKIP ] || [ "$TRAVIS_SECURE_ENV_VARS" != "true" ] || (go get -u github.com/gokrazy/autoupdate/cmd/gokr-amend && gokr-amend -set_label=please-boot *.bin *.elf *.dat)'
